defaultNamespace: monitoring

helm:
  chart: prometheus
  repo: https://prometheus-community.github.io/helm-charts
  version: 25.26.0
  releaseName: prometheus
  values:
    server:
      ingress:
        enabled: true
        ingressClassName: traefik
        annotations: 
          cert-manager.io/issuer: rancher
          cert-manager.io/issuer-kind: Issuer
          spec.ingressClassName: traefik
          traefik.ingress.kubernetes.io/router.middlewares: monitoring-prometheus-basic-auth@kubernetescrd
        hosts:
          - prometheus.moozo.co
        path: /
        pathType: Prefix
        tls:
          - secretName: prometheus-server-tls
            hosts:
              - prometheus.moozo.co
    alertmanager:
      ingress:
        enabled: true
        className: "traefik"
        annotations:
          cert-manager.io/issuer: rancher
          cert-manager.io/issuer-kind: Issuer
          spec.ingressClassName: traefik
          traefik.ingress.kubernetes.io/router.middlewares: monitoring-prometheus-basic-auth@kubernetescrd
        hosts:
          - host: alertmanager.moozo.co
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: alertmanager-server-tls
            hosts:
              - alertmanager.moozo.co
