defaultNamespace: monitoring

helm:
  chart: grafana
  repo: https://grafana.github.io/helm-charts
  version: 8.5.7
  releaseName: grafana
  values:
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
          cert-manager.io/issuer: rancher
          cert-manager.io/issuer-kind: Issuer
      path: /
      pathType: Prefix
      hosts:
        - grafana.moozo.co
      tls:
        - secretName: grafana-server-tls
          hosts:
            - grafana.moozo.co
